"""
QR code scanner – idle / low-power mode.

Uses picamera2 at low resolution to detect QR codes generated by the
vidaugment viewer.html.  A valid QR encodes a capture URL like:

    https://host/index.html?masterSessionId=<ID>

The scanner extracts and returns the masterSessionId.
"""

import logging
import re
import time
from urllib.parse import parse_qs, urlparse

import numpy as np
from pyzbar import pyzbar

from . import config

log = logging.getLogger(__name__)

# Pattern: URL that contains a masterSessionId query parameter
_SESSION_RE = re.compile(r"masterSessionId=([A-Za-z0-9_-]+)")


def extract_master_session_id(data: str) -> str | None:
    """Return the masterSessionId from a QR payload, or None."""
    m = _SESSION_RE.search(data)
    if m:
        return m.group(1)
    # Fallback: try formal URL parse
    try:
        parsed = urlparse(data)
        qs = parse_qs(parsed.query)
        ids = qs.get("masterSessionId", [])
        if ids and ids[0].strip():
            return ids[0].strip()
    except Exception:
        pass
    return None


def scan_frame(frame):
    """Decode QR codes in a numpy frame and return a masterSessionId or None."""
    # Convert to grayscale for faster pyzbar decoding
    if frame.ndim == 3:
        gray = frame[:, :, 1]  # green channel – best contrast
    else:
        gray = frame

    # Try raw grayscale first (fastest path)
    results = pyzbar.decode(gray, symbols=[pyzbar.ZBarSymbol.QRCODE])
    if not results:
        # Enhance contrast with adaptive thresholding for difficult lighting
        mean = np.mean(gray)
        enhanced = np.clip((gray.astype(np.int16) - mean) * 2 + 128, 0, 255).astype(np.uint8)
        results = pyzbar.decode(enhanced, symbols=[pyzbar.ZBarSymbol.QRCODE])

    for result in results:
        data = result.data.decode("utf-8", errors="replace")
        session_id = extract_master_session_id(data)
        if session_id:
            log.info("QR detected – masterSessionId=%s", session_id)
            return session_id
    return None


def run_scanner(picam2, shutdown_check=None) -> str | None:
    """
    Block until a QR code with a valid masterSessionId is found.

    *picam2* must already be configured and started in the low-res preview
    mode.  Returns the masterSessionId string, or None if shutdown requested.

    *shutdown_check* is an optional callable returning True when the process
    should exit (used for prompt SIGTERM handling).
    """
    log.info(
        "QR scanner active – looking for viewer QR code (%dx%d @ %d fps)",
        config.QR_SCAN_WIDTH,
        config.QR_SCAN_HEIGHT,
        config.QR_SCAN_FPS,
    )

    while True:
        if shutdown_check and shutdown_check():
            return None
        frame = picam2.capture_array("main")
        session_id = scan_frame(frame)
        if session_id:
            return session_id
